### ISSUE TITLE
Connecting Two AirPods with one iPhone 

### ISSUE THREAD

**Issue by osamainam777** [RobotPajamas/SwiftyTeeth#40]
Hi,
I am working on a project in which I need to connect two AirPods with single iPhone. 
Is it possible to do it?

Thanks & Cheers

**Comment by sureshjoshi** [comment]
I don't have any Airpods, but what about this?
https://www.redmondpie.com/ios-13-connect-or-share-2-airpods-simultaneously-on-iphone-or-ipad-heres-how/

**Comment by osamainam777** [comment]
Actually I am looking for a way to connect two or more Airpods using my own custom app.

**Comment by sureshjoshi** [comment]
Ah, okay, no clue. I've never used Airpods, so I don't know if they're even connectable.
